export { default as Vacancy } from "./Vacancy";
export { default as Contact } from "./Contact";
export { default as About } from "./About";
export { default as Shops } from "./Shops";
export { default as Gallery } from "./Gallery";
export { default as Products } from "./Products";
export { default as ProductDetail } from "./ProductDetail";
export { default as ErrorPage } from "./ErrorPage";
export { default as Home } from "./Home";
